import Foundation

struct AppLocalization: Sendable {
    let language: AppLanguage

    var locale: Locale {
        switch resolvedLanguageCode {
        case "zh-Hans":
            Locale(identifier: "zh-Hans")
        case "fr":
            Locale(identifier: "fr")
        default:
            language == .system ? .current : Locale(identifier: "en")
        }
    }

    var resolvedLanguageCode: String {
        switch language {
        case .system:
            let preferred = Locale.preferredLanguages.first?.lowercased() ?? "en"
            if preferred.hasPrefix("zh") { return "zh-Hans" }
            if preferred.hasPrefix("fr") { return "fr" }
            return "en"
        case .english:
            return "en"
        case .simplifiedChinese:
            return "zh-Hans"
        case .french:
            return "fr"
        }
    }

    func text(_ key: String) -> String {
        Self.translations[resolvedLanguageCode]?[key] ?? key
    }

    func text(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), locale: locale, arguments: arguments)
    }

    func text(_ key: String, arguments: [CVarArg]) -> String {
        String(format: text(key), locale: locale, arguments: arguments)
    }

    func languageDisplayName(for language: AppLanguage) -> String {
        switch language {
        case .system:
            return text("System")
        case .english:
            return "English"
        case .simplifiedChinese:
            return "简体中文"
        case .french:
            return "Français"
        }
    }

    private static let translations: [String: [String: String]] = [
        "zh-Hans": [
            "Ready": "就绪",
            "System": "跟随系统",
            "NotesBridge Settings": "NotesBridge 设置",
            "Distribution": "发行方式",
            "Build": "构建",
            "Language": "语言",
            "Direct Download": "直接下载版",
            "Mac App Store": "Mac App Store",
            "This build can enhance Apple Notes inline through Accessibility.": "此版本可通过辅助功能为 Apple Notes 提供行内增强。",
            "This build only exposes settings, sync, and integration features.": "此版本仅提供设置、同步和集成功能。",
            "Updates": "更新",
            "Version": "版本",
            "Build Number": "构建号",
            "Check for Updates...": "检查更新...",
            "Automatically check for updates": "自动检查更新",
            "Automatically download and install updates": "自动下载并安装更新",
            "NotesBridge checks GitHub Releases through Sparkle for direct-download updates.": "NotesBridge 通过 Sparkle 检查 GitHub Releases 中的直装版更新。",
            "Permissions": "权限",
            "Launch Mode": "启动方式",
            "Bundled App": "打包应用",
            "Command-line build": "命令行构建",
            "Accessibility": "辅助功能",
            "Granted": "已授予",
            "Required": "需要授权",
            "Recommended": "建议开启",
            "App Management": "应用管理",
            "Request Accessibility Permission": "请求辅助功能权限",
            "Open Accessibility Settings": "打开辅助功能设置",
            "Request App Management Permission": "请求应用管理权限",
            "Open App Management Settings": "打开应用管理设置",
            "Reveal NotesBridge App in Finder": "在 Finder 中显示 NotesBridge",
            "Relaunch as Bundled App": "以打包应用方式重新启动",
            "If NotesBridge is already checked in Accessibility but still shows Required here, remove it and add the current NotesBridge.app bundle again.": "如果系统中已勾选 NotesBridge，但这里仍显示需要授权，请移除后重新添加当前的 NotesBridge.app。",
            "Enable App Management for NotesBridge to let direct-download updates replace the installed app automatically.": "建议为 NotesBridge 开启应用管理权限，以便直装版更新能自动替换已安装的应用。",
            "Inline Enhancements": "行内增强",
            "Enable inline Apple Notes enhancements": "启用 Apple Notes 行内增强",
            "Inline Toolbar": "行内工具栏",
            "Enable Inline Toolbar": "启用行内工具栏",
            "Customize...": "自定义...",
            "Slash Commands": "斜杠命令",
            "Markdown": "Markdown",
            "Enable Markdown": "启用 Markdown",
            "Show formatting bar for selected text": "为选中文本显示格式栏",
            "Enable markdown and list triggers at line start": "启用行首 Markdown 和列表触发器",
            "Enable slash commands": "启用斜杠命令",
            "Customize Inline Toolbar": "自定义行内工具栏",
            "Reorder items and choose which ones are visible in the inline toolbar.": "调整顺序并选择哪些项目显示在行内工具栏中。",
            "Customize Slash Commands": "自定义斜杠命令",
            "Reorder slash commands and choose which ones are visible in the slash menu.": "调整斜杠命令顺序并选择哪些项目显示在斜杠菜单中。",
            "Reset to Default": "恢复默认",
            "Done": "完成",
            "Use / to open slash suggestions, or type an exact slash command and press Space to apply it inline.": "输入 / 打开斜杠建议，或输入完整斜杠命令后按空格直接应用。",
            "Keyboard slash navigation is unavailable in the current build. Use the mouse, or type an exact slash command and press Space.": "当前构建不支持键盘导航斜杠菜单。请使用鼠标，或输入完整斜杠命令后按空格。",
            "Inline enhancements support the formatting bar, markdown/list triggers, and slash commands.": "行内增强支持格式栏、Markdown/列表触发器和斜杠命令。",
            "Obsidian": "Obsidian",
            "Vault": "库",
            "Not configured": "未配置",
            "Choose Vault": "选择库",
            "Reveal in Finder": "在 Finder 中显示",
            "Export Folder Name": "导出目录名",
            "Attachments": "附件",
            "Use Obsidian attachment folder from .obsidian/app.json": "使用 .obsidian/app.json 中的附件目录",
            "Default Attachment Folder": "默认附件目录",
            "Resolved Folder": "实际目录",
            "Apple Notes attachments are stored in one shared root and keep the exported folder hierarchy underneath it.": "Apple Notes 附件存放在统一根目录下，并保留导出的层级结构。",
            "Apple Notes Data": "Apple Notes 数据",
            "Folder": "文件夹",
            "Access": "访问状态",
            "Accessible": "可访问",
            "Limited": "受限",
            "Invalid": "无效",
            "Choose Apple Notes Data Folder": "选择 Apple Notes 数据目录",
            "Choose the macOS Apple Notes container folder named group.com.apple.notes so NotesBridge can read NoteStore.sqlite and native attachments.": "请选择名为 group.com.apple.notes 的 macOS Apple Notes 容器目录，以便 NotesBridge 读取 NoteStore.sqlite 和原生附件。",
            "Indexing & Sync": "索引与同步",
            "Known Folders": "已知文件夹",
            "Indexed Notes": "已索引笔记",
            "Last Sync": "上次同步",
            "Last Full Sync": "上次完整同步",
            "Never": "从未",
            "Enable Automatic Sync": "启用自动同步",
            "Automatic Sync Interval": "自动同步间隔",
            "Every 30 minutes": "每 30 分钟",
            "Every hour": "每小时",
            "Every 6 hours": "每 6 小时",
            "Every day": "每天",
            "Refresh Folder Index": "刷新文件夹索引",
            "Syncing...": "同步中...",
            "Sync Changed Notes": "同步变更的笔记",
            "Run Full Sync": "执行完整同步",
            "Sync All Notes to Obsidian": "同步全部笔记到 Obsidian",
            "Current Status": "当前状态",
            "Current selection: %@": "当前选择：%@",
            "Slash commands: %@": "斜杠命令：%@",
            "Slash diagnostics": "斜杠诊断",
            "Title": "标题",
            "Heading": "标题 2",
            "Subheading": "标题 3",
            "Body": "正文",
            "Bold": "加粗",
            "Strikethrough": "删除线",
            "Monostyled": "等宽文本",
            "Checklist": "清单",
            "Bulleted List": "项目符号列表",
            "Dashed List": "短横线列表",
            "Numbered List": "编号列表",
            "Block Quote": "引用块",
            "Link": "链接",
            "Table": "表格",
            "Preparing sync progress...": "正在准备同步进度...",
            "Inline": "行内增强",
            "Slash": "斜杠",
            "Selection": "选择",
            "Sync": "同步",
            "Last sync: %@": "上次同步：%@",
            "Last full sync: %@": "上次完整同步：%@",
            "Open Apple Notes": "打开 Apple Notes",
            "Syncing Notes...": "正在同步笔记...",
            "Open Settings": "打开设置",
            "Quit NotesBridge": "退出 NotesBridge",
            "OK": "好",
            "No text selected": "未选择文本",
            "Selected text ready": "选中文本已就绪",
            "Slash commands are unavailable in the Mac App Store build.": "Mac App Store 版本不提供斜杠命令。",
            "Slash commands are disabled with inline enhancements.": "行内增强关闭时，斜杠命令不可用。",
            "Slash commands are turned off in Settings.": "设置中已关闭斜杠命令。",
            "No slash commands are enabled in Settings.": "设置中没有启用任何斜杠命令。",
            "Accessibility permission is required for slash commands.": "斜杠命令需要辅助功能权限。",
            "Accessibility permission is required for slash commands. If NotesBridge is already checked in Accessibility, remove and re-add the current app bundle once.": "斜杠命令需要辅助功能权限。如果系统中已勾选 NotesBridge，请移除后重新添加当前应用。",
            "Bring Apple Notes to the front to use slash commands.": "请将 Apple Notes 切到前台以使用斜杠命令。",
            "Focus the Apple Notes editor to use slash commands.": "请聚焦 Apple Notes 编辑器以使用斜杠命令。",
            "Slash commands are active. Use the mouse, or complete an exact slash command and press Space.": "斜杠命令已启用。请使用鼠标，或输入完整斜杠命令后按空格。",
            "Type / for suggestions, or complete a slash command and press Space.": "输入 / 查看建议，或输入完整斜杠命令后按空格。",
            "Inline enhancements are disabled in the Mac App Store build.": "Mac App Store 版本已禁用行内增强。",
            "Grant Accessibility to NotesBridge. If it is already checked, remove and re-add the current app bundle once.": "请为 NotesBridge 授予辅助功能权限。如果系统中已勾选，请移除后重新添加当前应用。",
            "Accessibility permission is required for Notes enhancements.": "Notes 增强功能需要辅助功能权限。",
            "Inline enhancements are disabled in Settings.": "设置中已关闭行内增强。",
            "Bring Apple Notes to the front to enable formatting tools.": "请将 Apple Notes 切到前台以启用格式工具。",
            "Focus the Apple Notes editor to use inline formatting tools.": "请聚焦 Apple Notes 编辑器以使用行内格式工具。",
            "Inline enhancements are active in Apple Notes.": "Apple Notes 行内增强已启用。",
            "Requesting Accessibility permission for NotesBridge...": "正在为 NotesBridge 请求辅助功能权限...",
            "Accessibility is already granted for NotesBridge.": "NotesBridge 已获得辅助功能权限。",
            "Open Privacy & Security > Accessibility and enable NotesBridge. If it is missing, add ~/Library/Application Support/NotesBridge/NotesBridge.app manually.": "请打开 隐私与安全性 > 辅助功能 并启用 NotesBridge。如果列表中没有，请手动添加 ~/Library/Application Support/NotesBridge/NotesBridge.app。",
            "Open Privacy & Security > Accessibility and enable NotesBridge.": "请打开 隐私与安全性 > 辅助功能 并启用 NotesBridge。",
            "Open Privacy & Security > App Management and enable NotesBridge so direct-download updates can replace the installed app.": "请打开 隐私与安全性 > 应用管理，并为 NotesBridge 启用权限，以便直装版更新可以替换已安装的应用。",
            "Requesting Input Monitoring permission for slash menu keyboard navigation...": "正在为斜杠菜单键盘导航请求输入监控权限...",
            "Input Monitoring is already granted for NotesBridge.": "NotesBridge 已获得输入监控权限。",
            "Open Privacy & Security > Input Monitoring to enable slash menu keyboard navigation for NotesBridge.": "请打开 隐私与安全性 > 输入监控，为 NotesBridge 启用斜杠菜单键盘导航。",
            "Relaunching NotesBridge as a bundled app so macOS can grant Input Monitoring...": "正在以打包应用方式重新启动 NotesBridge，以便 macOS 授予输入监控权限...",
            "Relaunching NotesBridge as a bundled app...": "正在以打包应用方式重新启动 NotesBridge...",
            "Failed to relaunch NotesBridge as a bundled app.": "无法以打包应用方式重新启动 NotesBridge。",
            "Choose an Obsidian vault": "选择一个 Obsidian 库",
            "Use Vault": "使用此库",
            "Obsidian vault set to %@.": "Obsidian 库已设置为 %@。",
            "Apple Notes data folder set to %@.": "Apple Notes 数据目录已设置为 %@。",
            "Failed to access Apple Notes data folder.": "无法访问 Apple Notes 数据目录。",
            "Sync cancelled. Choose the Apple Notes data folder to continue.": "同步已取消。请选择 Apple Notes 数据目录以继续。",
            "Refreshing Apple Notes folders...": "正在刷新 Apple Notes 文件夹...",
            "Loaded %lld Apple Notes folders.": "已加载 %lld 个 Apple Notes 文件夹。",
            "Failed to refresh Apple Notes folders.": "无法刷新 Apple Notes 文件夹。",
            "Choose an Obsidian vault before syncing.": "同步前请先选择一个 Obsidian 库。",
            "Checking Apple Notes for changes...": "正在检查 Apple Notes 是否有变更...",
            "Syncing changed Apple Notes to Obsidian...": "正在将变更的 Apple Notes 同步到 Obsidian...",
            "Running a full Apple Notes sync...": "正在执行完整 Apple Notes 同步...",
            "Syncing Apple Notes to Obsidian...": "正在将 Apple Notes 同步到 Obsidian...",
            "No Apple Notes changes were found.": "未发现 Apple Notes 变更。",
            "Processed %lld note(s) and found no changes.": "已处理 %lld 条笔记，未发现变更。",
            "Processed %lld note(s): updated %lld, added %lld, moved %lld to _Removed, and left %lld unchanged.": "已处理 %lld 条笔记：更新 %lld 条，新增 %lld 条，移到 _Removed %lld 条，未变化 %lld 条。",
            "Incremental sync could not load %lld changed note(s) by ID, so it fell back to a full sync.": "增量同步有 %lld 条变更笔记无法按 ID 读取正文，因此已回退到完整同步。",
            "Full sync: %@": "完整同步：%@",
            "Incremental sync could not load %lld changed note(s) by ID, so it fell back to a full sync. %@": "增量同步有 %lld 条变更笔记无法按 ID 读取正文，因此已回退到完整同步。%@",
            "Failed to sync changed Apple Notes to Obsidian.": "无法将变更的 Apple Notes 同步到 Obsidian。",
            "Processed %lld note(s) across %lld folder(s): updated %lld, added %lld.": "已处理 %lld 条笔记，涉及 %lld 个文件夹：更新 %lld 条，新增 %lld 条。",
            "Processed %lld note(s) across %lld folder(s): updated %lld, added %lld, and left %lld unchanged.": "已处理 %lld 条笔记，涉及 %lld 个文件夹：更新 %lld 条，新增 %lld 条，未变化 %lld 条。",
            "Failed to sync Apple Notes to Obsidian.": "无法将 Apple Notes 同步到 Obsidian。",
            "Failed to save app settings.": "无法保存应用设置。",
            "%d%% • %d/%d notes • %d/%d folders": "%d%% • %d/%d 条笔记 • %d/%d 个文件夹",
            "Current folder: %@": "当前文件夹：%@"
        ],
        "fr": [
            "Ready": "Prêt",
            "System": "Système",
            "NotesBridge Settings": "Réglages NotesBridge",
            "Distribution": "Distribution",
            "Build": "Build",
            "Language": "Langue",
            "Direct Download": "Téléchargement direct",
            "Mac App Store": "Mac App Store",
            "This build can enhance Apple Notes inline through Accessibility.": "Cette version peut enrichir Apple Notes en ligne via Accessibilité.",
            "This build only exposes settings, sync, and integration features.": "Cette version n'expose que les réglages, la synchronisation et les intégrations.",
            "Updates": "Mises à jour",
            "Version": "Version",
            "Build Number": "Numéro de build",
            "Check for Updates...": "Rechercher des mises à jour...",
            "Automatically check for updates": "Rechercher automatiquement les mises à jour",
            "Automatically download and install updates": "Télécharger et installer automatiquement les mises à jour",
            "NotesBridge checks GitHub Releases through Sparkle for direct-download updates.": "NotesBridge vérifie les mises à jour du téléchargement direct sur GitHub Releases via Sparkle.",
            "Permissions": "Autorisations",
            "Launch Mode": "Mode de lancement",
            "Bundled App": "App empaquetée",
            "Command-line build": "Build en ligne de commande",
            "Accessibility": "Accessibilité",
            "Granted": "Accordé",
            "Required": "Requis",
            "Recommended": "Recommandé",
            "App Management": "Gestion des apps",
            "Request Accessibility Permission": "Demander l'autorisation Accessibilité",
            "Open Accessibility Settings": "Ouvrir les réglages Accessibilité",
            "Request App Management Permission": "Demander l'autorisation Gestion des apps",
            "Open App Management Settings": "Ouvrir les réglages Gestion des apps",
            "Reveal NotesBridge App in Finder": "Afficher NotesBridge dans le Finder",
            "Relaunch as Bundled App": "Relancer comme app empaquetée",
            "Enable App Management for NotesBridge to let direct-download updates replace the installed app automatically.": "Activez Gestion des apps pour NotesBridge afin que les mises à jour du téléchargement direct puissent remplacer automatiquement l’application installée.",
            "Inline Enhancements": "Améliorations en ligne",
            "Enable inline Apple Notes enhancements": "Activer les améliorations Apple Notes en ligne",
            "Inline Toolbar": "Barre d’outils inline",
            "Enable Inline Toolbar": "Activer la barre d’outils inline",
            "Customize...": "Personnaliser...",
            "Slash Commands": "Commandes slash",
            "Markdown": "Markdown",
            "Enable Markdown": "Activer Markdown",
            "Show formatting bar for selected text": "Afficher la barre de formatage pour le texte sélectionné",
            "Enable markdown and list triggers at line start": "Activer les déclencheurs Markdown et listes en début de ligne",
            "Enable slash commands": "Activer les commandes slash",
            "Customize Inline Toolbar": "Personnaliser la barre d’outils inline",
            "Reorder items and choose which ones are visible in the inline toolbar.": "Réorganisez les éléments et choisissez ceux qui restent visibles dans la barre d’outils inline.",
            "Customize Slash Commands": "Personnaliser les commandes slash",
            "Reorder slash commands and choose which ones are visible in the slash menu.": "Réorganisez les commandes slash et choisissez celles qui restent visibles dans le menu slash.",
            "Reset to Default": "Réinitialiser",
            "Done": "Terminé",
            "Obsidian": "Obsidian",
            "Vault": "Vault",
            "Not configured": "Non configuré",
            "Choose Vault": "Choisir un vault",
            "Reveal in Finder": "Afficher dans le Finder",
            "Export Folder Name": "Nom du dossier d'export",
            "Attachments": "Pièces jointes",
            "Default Attachment Folder": "Dossier des pièces jointes par défaut",
            "Resolved Folder": "Dossier résolu",
            "Apple Notes Data": "Données Apple Notes",
            "Folder": "Dossier",
            "Access": "Accès",
            "Accessible": "Accessible",
            "Limited": "Limité",
            "Invalid": "Invalide",
            "Choose Apple Notes Data Folder": "Choisir le dossier de données Apple Notes",
            "Indexing & Sync": "Indexation et synchronisation",
            "Known Folders": "Dossiers connus",
            "Indexed Notes": "Notes indexées",
            "Last Sync": "Dernière synchro",
            "Last Full Sync": "Dernière synchro complète",
            "Never": "Jamais",
            "Enable Automatic Sync": "Activer la synchronisation automatique",
            "Automatic Sync Interval": "Intervalle de synchronisation automatique",
            "Every 30 minutes": "Toutes les 30 minutes",
            "Every hour": "Toutes les heures",
            "Every 6 hours": "Toutes les 6 heures",
            "Every day": "Tous les jours",
            "Refresh Folder Index": "Rafraîchir l'index des dossiers",
            "Syncing...": "Synchronisation...",
            "Sync Changed Notes": "Synchroniser les notes modifiées",
            "Run Full Sync": "Lancer une synchro complète",
            "Sync All Notes to Obsidian": "Synchroniser toutes les notes vers Obsidian",
            "Current Status": "État actuel",
            "Current selection: %@": "Sélection actuelle : %@",
            "Slash commands: %@": "Commandes slash : %@",
            "Slash diagnostics": "Diagnostic slash",
            "Title": "Titre",
            "Heading": "Titre 2",
            "Subheading": "Titre 3",
            "Body": "Corps",
            "Bold": "Gras",
            "Strikethrough": "Barré",
            "Monostyled": "Monostyle",
            "Checklist": "Checklist",
            "Bulleted List": "Liste à puces",
            "Dashed List": "Liste à tirets",
            "Numbered List": "Liste numérotée",
            "Block Quote": "Bloc de citation",
            "Link": "Lien",
            "Table": "Tableau",
            "Preparing sync progress...": "Préparation de la progression...",
            "Inline": "Inline",
            "Slash": "Slash",
            "Selection": "Sélection",
            "Sync": "Sync",
            "Last sync: %@": "Dernière synchro : %@",
            "Last full sync: %@": "Dernière synchro complète : %@",
            "Open Apple Notes": "Ouvrir Apple Notes",
            "Syncing Notes...": "Synchronisation des notes...",
            "Open Settings": "Ouvrir les réglages",
            "Quit NotesBridge": "Quitter NotesBridge",
            "OK": "OK",
            "No text selected": "Aucun texte sélectionné",
            "Selected text ready": "Texte sélectionné prêt",
            "No slash commands are enabled in Settings.": "Aucune commande slash n’est activée dans les réglages.",
            "Refreshing Apple Notes folders...": "Actualisation des dossiers Apple Notes...",
            "Loaded %lld Apple Notes folders.": "%lld dossiers Apple Notes chargés.",
            "Failed to refresh Apple Notes folders.": "Échec de l'actualisation des dossiers Apple Notes.",
            "Choose an Obsidian vault before syncing.": "Choisissez un vault Obsidian avant la synchronisation.",
            "Checking Apple Notes for changes...": "Vérification des changements Apple Notes...",
            "Syncing changed Apple Notes to Obsidian...": "Synchronisation des notes Apple modifiées vers Obsidian...",
            "Running a full Apple Notes sync...": "Exécution d'une synchronisation Apple Notes complète...",
            "Syncing Apple Notes to Obsidian...": "Synchronisation d'Apple Notes vers Obsidian...",
            "No Apple Notes changes were found.": "Aucun changement Apple Notes n'a été détecté.",
            "Processed %lld note(s) and found no changes.": "%lld note(s) traitée(s), aucun changement détecté.",
            "Processed %lld note(s): updated %lld, added %lld, moved %lld to _Removed, and left %lld unchanged.": "%lld note(s) traitée(s) : %lld mise(s) à jour, %lld ajoutée(s), %lld déplacée(s) vers _Removed, %lld inchangée(s).",
            "Incremental sync could not load %lld changed note(s) by ID, so it fell back to a full sync.": "La synchronisation incrémentielle n’a pas pu charger %lld note(s) modifiée(s) par identifiant, elle est donc revenue à une synchronisation complète.",
            "Full sync: %@": "Synchronisation complète : %@",
            "Incremental sync could not load %lld changed note(s) by ID, so it fell back to a full sync. %@": "La synchronisation incrémentielle n’a pas pu charger %lld note(s) modifiée(s) par identifiant, elle est donc revenue à une synchronisation complète. %@",
            "Failed to sync changed Apple Notes to Obsidian.": "Échec de la synchronisation des notes Apple modifiées vers Obsidian.",
            "Open Privacy & Security > App Management and enable NotesBridge so direct-download updates can replace the installed app.": "Ouvrez Confidentialité et sécurité > Gestion des apps et activez NotesBridge afin que les mises à jour du téléchargement direct puissent remplacer l’application installée.",
            "Processed %lld note(s) across %lld folder(s): updated %lld, added %lld.": "%lld note(s) traitée(s) dans %lld dossier(s) : %lld mise(s) à jour, %lld ajoutée(s).",
            "Processed %lld note(s) across %lld folder(s): updated %lld, added %lld, and left %lld unchanged.": "%lld note(s) traitée(s) dans %lld dossier(s) : %lld mise(s) à jour, %lld ajoutée(s), %lld inchangée(s).",
            "Failed to sync Apple Notes to Obsidian.": "Échec de la synchronisation d'Apple Notes vers Obsidian.",
            "%d%% • %d/%d notes • %d/%d folders": "%d%% • %d/%d notes • %d/%d dossiers",
            "Current folder: %@": "Dossier actuel : %@"
        ]
    ]
}
